name: CI-CD Docker

on:
    push:

permissions:
    contents: read
    packages: write

jobs:
    buld-test-push:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name : Build & Test Image (CI)
          run: |
              docker build -t my-image .
              docker run my-image pytest        

        - name: Log in to Github Container Registry
          run : echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Build Docker Image
          run: docker build -t ghcr.io/${{ github.repository }}/my-image:latest .

        - name: Push Docker Image
          run: docker push ghcr.io/${{ github.repository }}/my-image:latest
        
        - name: Deploy to EC2
          run: |
              echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
              chmod 600 key.pem

              ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@{{ secrets.EC2_HOST }} << 'EOF'

                  docker pull ghcr.io/${{ github.repository }}/my-image:latest

                  docker stop myapp ||true
                  docker rm myapp ||true

                  docker run -d -p 8000:8000 --name my-app ghcr.io/${{ github.repository }}/my-image:latest

              EOF