name: Mon premier workflow

on:
    push:

jobs:
    hello-jobs:
        runs-on: ubuntu-latest

        steps:
            - name: Afficher un message
              run: |
                echo "Im leaning GitHub Actions"
                echo "I want to be a DevOps Engineer"
                echo " This workflow works perfectly"