name: GitHub Token Demo

on:
    push:

jobs:
    api-call:
        runs-on: ubuntu-latest

        steps:
        - name: Call GitHub API
          run: |
            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/greeg75/github-actions-learning